{% set name = "janus" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df976f2cdcfb034b147a2d51edfc34ff6bfb12d4e2643d3ad0e10de058cb1612

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.5.3
  run:
    - python >=3.5.3
    - typing_extensions

test:
  imports:
    - janus

about:
  home: https://github.com/aio-libs/janus/
  license: Apache-2.0
  license_file: LICENSE
  summary: Mixed sync-async queue to interoperate between asyncio tasks and classic threads

extra:
  recipe-maintainers:
    - epruesse
    - thewchan
