{% set name = "janus" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df976f2cdcfb034b147a2d51edfc34ff6bfb12d4e2643d3ad0e10de058cb1612

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=51
    - wheel >=0.36
  run:
    - python
    - typing_extensions >=3.7.4.3

test:
  imports:
    - janus
  requires:
    - pip
    - pytest >=6.2.5
    - pytest-asyncio >=0.16.0
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/aio-libs/janus/
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  summary: Mixed sync-async queue to interoperate between asyncio tasks and classic threads
  description: |
    Mixed sync-async queue, supposed to be used for communicating between classic synchronous (threaded)
    code and asynchronous (in terms of asyncio) one.
    Like Janus god the queue object from the library has two faces: synchronous and asynchronous interface.
    Synchronous is fully compatible with standard queue, asynchronous one follows asyncio queue design.
  doc_url: https://github.com/aio-libs/janus
  dev_url: https://github.com/aio-libs/janus

extra:
  recipe-maintainers:
    - epruesse
    - thewchan
