{% set name = "janus" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4712e0ef75711fe5947c2db855bc96221a9a03641b52e5ae8e25c2b705dd1d0c

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.5.3
  run:
    - python >=3.5.3

test:
  imports:
    - janus

about:
  home: https://github.com/aio-libs/janus/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Mixed sync-async queue to interoperate between asyncio tasks and classic threads

extra:
  recipe-maintainers:
    - epruesse
