travis:
  secure:
    BINSTAR_TOKEN: QEPsObY4JWSW65sUOEaPxibQA/TlIoPVEOUjRnLA2A+vbVeZrW6cstYKzCr+XTayarmJfFq0UDV40C2SqmqMPDgHJm/MtxpojQVoFRnN1MPvJYNGu6tSgQ7vOXdC/uE5FWucfZW6jIL/u9B7oNiDXw1OytRgV2f08gbHAJvhDapcjjzbrm3JctQmlg9Lkui8DGWp4KfR9lbp4XVtUEQNLXLfGSsIAaPT5mKHADL2VLBQymrllDU/FulGide+ebZSbM+7ZN5atXyu7oR/E16JpMzu7VQ4boP5nN7S8iJxq0ONV3Y+1yXCGJmb4vXMC5tD/wHuxknbI51PRjWwbWpueURQ937pP4yGZOOIWiZn0zS3mG7xM3BKkJlu5egPtn3aZlrvOxWj8vDeNxfWkVqIbdzzhI4xw7/6hr8WbQ7MC8Z08nF49/P/XB5SMYa0gWjcXYQ3OHGjNG5qZ8XUNR98vXMOSm/YZln65abiGCZhW+q71LX05PfdXT94NWxQi+leZvZBF5sSvsiyBRraw/nirkbTN5bsT/7+pfR/wCW6jL9pmiXp1Y10H3IBe76Y3Pdh34oPH4lFg5bq2aunh6ZU+CteHsJDMpIiGDteIlopnRe/CllhtrH95DkvrpdxaNwi+t7jlrib5SMxEeVDdD4mdmD6FMBvxjs/3fbR7KBJqmU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
